// Generated by gencpp from file image/ping.msg
// DO NOT EDIT!


#ifndef IMAGE_MESSAGE_PING_H
#define IMAGE_MESSAGE_PING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace image
{
template <class ContainerAllocator>
struct ping_
{
  typedef ping_<ContainerAllocator> Type;

  ping_()
    : x(0)
    , y(0)
    , r(0)  {
    }
  ping_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , r(0)  {
  (void)_alloc;
    }



   typedef uint32_t _x_type;
  _x_type x;

   typedef uint32_t _y_type;
  _y_type y;

   typedef uint8_t _r_type;
  _r_type r;





  typedef boost::shared_ptr< ::image::ping_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::image::ping_<ContainerAllocator> const> ConstPtr;

}; // struct ping_

typedef ::image::ping_<std::allocator<void> > ping;

typedef boost::shared_ptr< ::image::ping > pingPtr;
typedef boost::shared_ptr< ::image::ping const> pingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::image::ping_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::image::ping_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace image

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'image': ['/home/jhj/catkin_ws/src/image/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::image::ping_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::image::ping_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::image::ping_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::image::ping_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image::ping_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image::ping_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::image::ping_<ContainerAllocator> >
{
  static const char* value()
  {
    return "43a9b7aca27bce58e13d112ff91c35ad";
  }

  static const char* value(const ::image::ping_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x43a9b7aca27bce58ULL;
  static const uint64_t static_value2 = 0xe13d112ff91c35adULL;
};

template<class ContainerAllocator>
struct DataType< ::image::ping_<ContainerAllocator> >
{
  static const char* value()
  {
    return "image/ping";
  }

  static const char* value(const ::image::ping_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::image::ping_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 x\n"
"uint32 y\n"
"uint8  r\n"
;
  }

  static const char* value(const ::image::ping_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::image::ping_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.r);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ping_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::image::ping_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::image::ping_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.y);
    s << indent << "r: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.r);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMAGE_MESSAGE_PING_H
